// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBen6hV6jJgQ_dKArarInsRryMTAlgrWlE',
    appId: '1:236074256386:android:5fd8bf2f22ca0a4aa13f1b',
    messagingSenderId: '236074256386',
    projectId: 'racing-app-8721e',
    storageBucket: 'racing-app-8721e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADYe-my7OViTbX7TUxMvBg8L599JvXKEU',
    appId: '1:236074256386:ios:f30f4817c5e4e787a13f1b',
    messagingSenderId: '236074256386',
    projectId: 'racing-app-8721e',
    storageBucket: 'racing-app-8721e.firebasestorage.app',
    iosBundleId: 'com.example.raceTrakingApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpRgYWPlZw2kPqHBdFk76lN9wMXplc7Oc',
    appId: '1:236074256386:web:3ea1815d99412d43a13f1b',
    messagingSenderId: '236074256386',
    projectId: 'racing-app-8721e',
    authDomain: 'racing-app-8721e.firebaseapp.com',
    storageBucket: 'racing-app-8721e.firebasestorage.app',
  );

}